# fly.toml app configuration file generated for fullstackopen-notesapp on 2023-11-23T19:58:40+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fullstackopen-notesapp"
primary_region = "mad"

[build]
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
